
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--c-4505143
clusters:
- name: shoot--kyma--c-4505143
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQWQ2Z0F3SUJBZ0lRZHV0cHpFQUl2YmcyOTNJWkhCNVcwREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEl5TURNeE5URXhORFUxTWxvWERUTXlNRE14TlRFeApORFUxTWxvd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTjQ2ZmYxZHlzS0FyR04zVGxoNkk1WEVKbVpoRlhTSG9YN1lMZ0pyY0dKSE9hdWIKQkdicEFSV2NkbjVBaWU0U21KQTd0N1h5L2hYQWs0YjFkYkZyUjg0RnRNMnlUSzh1NU9vMGhFSkM3YmYxRDMycApYaTh5Z1dnSXdTTVlaZ0NMazZUWm1CN0FEYU95ZXo2U3lVY1BzQ2pTOXVHY1Z6WndSb1M4dVFMd1dvVXovbHFFCm1Qejhjby8wZEQvZlhyUFlpcHliL0JzTVFTQldhYXY2VmxZL0xub1JHZndZTkZTbEF5c0ZhK0pxdTl0cW1QUVEKY3JBS1V0ek94S3FPeXVHVU9MRzVEYjhwOHFvMXdrNEd1NVNveFVBLzFVaTYxN1J3aFNjNHZORTRZT3F6UDE1ZwovOGFDWHQydXFJakVKQ3h5eTZYZEJpUU5yUXhlTzJxQ2diVGorWDhDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvCkJBUURBZ0dtTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk1xbEVQdGJPTDZqV0haLzRCQ1YKWWF1V2krN0FNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJOek1IaHgyZzN3UE5pS2hET3ZMVW9Oc2tsN2tIRQplNjNKeURXZGFibmlySDZaUWJJdndoTDZNU29lbHZ6MjBVcE1ib2phdzBFaEVlTmhCSldSYVpnUkRqVWxhM1VHCmlvYzdlUm15U0hLVGQvSHNYOUZKb0YrVGRMbmhqSnUzTDcxYlRrY09mbExBUmxtY05rSzNsTW14MDl1b0k0S2IKVHBJMFFRblRVR2ZRWm53Mlo3TTRNZng4azBRVDRWM1BJSTNYeEpNVjVzM1lVOGlUNWk5RnBjZkRMR3RvcTRGTQpGTUkwYkJvci9DeStXc2RnakU1L2tUR2hvNjgvdkY0S1ZXRlFPb2hLQkhvUTFaWlRDWVpvcmFQVkE5ZXdQSldYClh5a2xKbjd3b05xT2tzb3F5Q0NSbDRXOHNDQ3hmVCtwc3FTSU56UTZoWkpxQ1Vhbk1OWkZCdDVSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://api.c-4505143.kyma.ondemand.com
contexts:
- name: shoot--kyma--c-4505143
  context:
    cluster: shoot--kyma--c-4505143
    user: shoot--kyma--c-4505143
users:
- name: shoot--kyma--c-4505143
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
