apiVersion: v1
kind: Service
metadata:
  name: njs
  labels:
    app: njs
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: njs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: njs
spec:
  selector:
    matchLabels:
      app: njs
  replicas: 1
  template:
    metadata:
      labels:
        app: njs
    spec:
      containers:
        - image: zofllutz/njsbtp
          name: njs
          ports:
          - name: http
            containerPort: 3000